name: TGSpeicher
options:
  bundleIdPrefix: eu.simplexsmp
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  developmentLanguage: de
packages:
  TDLibFramework:
    url: https://github.com/Swiftgram/TDLibFramework
    revision: 52d0d624cd5b01db0558c9dec3e07148c62ac205
targets:
  TGSpeicher:
    type: application
    platform: iOS
    sources:
      - path: TGSpeicher
      - path: Shared
    dependencies:
      - target: TGSpeicherLiveActivity
        embed: true
      - package: TDLibFramework
        product: TDLibFramework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: eu.simplexsmp.tgspeicher
        PRODUCT_NAME: TGSpeicher
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1,2"
        INFOPLIST_FILE: TGSpeicher/Info.plist
        CURRENT_PROJECT_VERSION: 35
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        MARKETING_VERSION: 3.3.2
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: NO
    scheme:
      testTargets: []
      gatherCoverageData: false

  TGSpeicherLiveActivity:
    type: app-extension
    platform: iOS
    sources:
      - path: TGSpeicherLiveActivity
      - path: Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: eu.simplexsmp.tgspeicher.liveactivity
        PRODUCT_NAME: TGSpeicherLiveActivity
        INFOPLIST_FILE: TGSpeicherLiveActivity/Info.plist
        CURRENT_PROJECT_VERSION: 35
        MARKETING_VERSION: 3.3.2
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1,2"
        APPLICATION_EXTENSION_API_ONLY: YES
        SKIP_INSTALL: YES
        GENERATE_INFOPLIST_FILE: NO
        CODE_SIGN_STYLE: Automatic

